CREATE OR REPLACE TABLE retail_supply_data (
    row_id INT,
    order_id STRING,
    order_date DATE,
    ship_date DATE,
    ship_mode STRING,
    customer_id STRING,
    customer_name STRING,
    segment STRING,
    country STRING,
    city STRING,
    state STRING,
    postal_code STRING,
    region STRING,
    retail_sales_people STRING,
    product_id STRING,
    category STRING,
    sub_category STRING,
    product_name STRING,
    returned STRING,
    sales FLOAT,
    quantity INT,
    discount FLOAT,
    profit FLOAT
);
